### ISSUE TITLE
NullPointerException on recipe creation

### ISSUE THREAD

**Issue by Kezz101** [ShaneBeee/SkRecipe#1]
Not sure if this is an issue with my skript or an issue with SkRecipe, but I don't think it should be throwing a npe regardless. I also got the same error on my server running Java 1.8. The same error also happens for shapeless recipes.

**Error log**
```
[22:46:18 ERROR]: #!#!
[22:46:18 ERROR]: #!#! [Skript] Severe Error:
[22:46:18 ERROR]: #!#!
[22:46:18 ERROR]: #!#! Something went horribly wrong with Skript.
[22:46:18 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[22:46:18 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[22:46:18 ERROR]: #!#! Here is full list of them:
[22:46:18 ERROR]: #!#! SK-NBeeT (https://github.com/ShaneBeee/Sk-NBeeT)
[22:46:18 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[22:46:18 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[22:46:18 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[22:46:18 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[22:46:18 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[22:46:18 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[22:46:18 ERROR]: #!#!
[22:46:18 ERROR]: #!#! Stack trace:
[22:46:18 ERROR]: #!#! java.lang.NullPointerException
[22:46:18 ERROR]: #!#!     at tk.shanebee.skrecipe.elements.effects.EffCraftingRecipe.registerShaped(EffCraftingRecipe.java:81)
[22:46:18 ERROR]: #!#!     at tk.shanebee.skrecipe.elements.effects.EffCraftingRecipe.execute(EffCraftingRecipe.java:72)[22:46:18 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[22:46:18 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[22:46:18 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[22:46:18 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:57)
[22:46:18 ERROR]: #!#!     at ch.njol.skript.events.EvtSkript.onSkriptStart(EvtSkript.java:65)
[22:46:18 ERROR]: #!#!     at ch.njol.skript.Skript$2.run(Skript.java:538)
[22:46:18 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
[22:46:18 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
[22:46:18 ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171)
[22:46:18 ERROR]: #!#!     at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417)
[22:46:18 ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098)
[22:46:18 ERROR]: #!#!     at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925)
[22:46:18 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:834)
[22:46:18 ERROR]: #!#!
[22:46:18 ERROR]: #!#! Version Information:
[22:46:18 ERROR]: #!#!   Skript: 2.4-beta10 (latest)
[22:46:18 ERROR]: #!#!     Flavor: skriptlang-github
[22:46:18 ERROR]: #!#!     Date: 2019-11-11
[22:46:18 ERROR]: #!#!   Bukkit: 1.14.4-R0.1-SNAPSHOT
[22:46:18 ERROR]: #!#!   Minecraft: 1.14.4
[22:46:18 ERROR]: #!#!   Java: 11.0.2 (Java HotSpot(TM) 64-Bit Server VM 11.0.2+9-LTS)
[22:46:18 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[22:46:18 ERROR]: #!#!
[22:46:18 ERROR]: #!#! Server platform: Paper
[22:46:18 ERROR]: #!#!
[22:46:18 ERROR]: #!#! Current node: null
[22:46:18 ERROR]: #!#! Current item: Register new shaped recipe for {_warpStone}(as ch.njol.skript.aliases.ItemType) using ([[itemtype:emerald]], [[itemtype:ender pearl]], [[itemtype:emerald]], [[itemtype:ender pearl]], [[itemtype:blaze powder]], [[itemtype:ender pearl]], [[itemtype:emerald]], [[itemtype:ender pearl]] and [[itemtype:emerald]])[class ch.njol.skript.aliases.ItemType] with id "warp_stone" in group "warp_stones"
[22:46:18 ERROR]: #!#! Current trigger: skript load (on server start) (warp stones.sk, line 1)
[22:46:18 ERROR]: #!#!
[22:46:18 ERROR]: #!#! Thread: Server thread
[22:46:18 ERROR]: #!#!
[22:46:18 ERROR]: #!#! Language: english
[22:46:18 ERROR]: #!#! Link parse mode: DISABLED
[22:46:18 ERROR]: #!#!
[22:46:18 ERROR]: #!#! End of Error.
[22:46:18 ERROR]: #!#!
```

**Skript**
```
on skript load:
    set {warpStone} to minecart with command block named "&bWarp Stone"
    set {ironWarpStone} to minecart with command block named "&bIron Warp Stone" with model data 1
    set {goldWarpStone} to minecart with command block named "&bGold Warp Stone" with model data 2
    set {diamondWarpStone} to minecart with command block named "&bDiamond Warp Stone" with model data 3
    
    register new shaped recipe for {_warpStone} using emerald, ender pearl, emerald, ender pearl, blaze powder, ender pearl, emerald, ender pearl and emerald with id "warp_stone" in group "warp_stones"
    register new shaped recipe for {_ironWarpStone} using iron ingot, ender pearl, iron ingot, ender pearl, {_warpStone}, ender pearl, iron ingot, ender pearl and emerald with id "iron_warp_stone" in group "warp_stones"
    register new shaped recipe for {_goldWarpStone} using gold ingot, ender pearl, gold ingot, ender pearl, {_ironWarpStone}, ender pearl, gold ingot, ender pearl and gold ingot with id "gold_warp_stone" in group "warp_stones"
    register new shaped recipe for {_diamondWarpStone} using diamond, ender pearl, diamond, ender pearl, {_goldWarpStone}, ender pearl, diamond, ender pearl and diamond with id "diamond_warp_stone" in group "warp_stones"
```

**Comment by ShaneBeee** [comment]
My guess is its due to the fact you are setting a global variable to an item, but then using a local variable in the recipe:

<img width="910" alt="Screen Shot 2019-11-12 at 2 58 17 PM" src="https://user-images.githubusercontent.com/20008482/68717999-f55f1200-055c-11ea-81cf-5091a8e81111.png">

**Comment by Kezz101** [comment]
Wow yup that's exactly it.. I feel very blind now. Sorry for ruining your first issue with something so garbage! :')

**Comment by ShaneBeee** [comment]
OMG not ruined at all. I still have to fix the issue so thanks for bringing this to my attention.
Im just adding a null check so at least if this happens it won't throw an error.

**Comment by Kezz101** [comment]
I did note that the Skript error log doesn't show that I'm using SkRecipe - I'm not sure how Skript shows a list of addons but adding SkRecipe to that list could be issue number two

**Comment by ShaneBeee** [comment]
Yeah I noticed that too, that is really odd. I'm not entirely sure why that is happening.

**Comment by ShaneBeee** [comment]
This has now been fixed and released, if you create a recipe and its missing an ingredient or result it will now throw a nicer error telling you what is wrong:

<img width="779" alt="Screen Shot 2019-11-12 at 3 43 08 PM" src="https://user-images.githubusercontent.com/20008482/68720133-26dadc00-0563-11ea-9083-6ae52887f181.png">
